version: '3.8'
services:
  app:
    build:
      context: ./docker/php
    volumes:
      - .:/var/www
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"